### ISSUE TITLE
Create a "classroom" image

### ISSUE THREAD

**Issue by colearendt** [rstudio/sol-eng-demo-server#22]
This image will mirror (as much as possible) the "classroom" images that we use for the training-tool infrastructure.

**Comment by akgold** [comment]
An image? Or a container?

**Comment by colearendt** [comment]
Yes - docker image for sure 😄Container = image running

The analog for AWS land is AMI (Amazon Machine Image) vs. Instance

```
AMI:Instance::Docker Image:Container
```

**Comment by akgold** [comment]
Understood. When you said Image, my mind went to an AMI :)

**Comment by akgold** [comment]
Any ideas here on what acceptance criteria would be? Should I just grab a Phil example and run through?

**Comment by colearendt** [comment]
Yeah, I say we just do our best to keep in sync 😄No pressure IMO. Something is better than nothing, I suspect!

**Comment by akgold** [comment]
Here are 2 phil repos I can test with:
https://github.com/philbowsher/Foundation-of-the-R-Workflow-workshop-2019-09-06
https://github.com/philbowsher/phuse-ML12-R-Tensorflow-Immunotherapy

**Comment by akgold** [comment]
Notes on what we need:
- Fixed DSN to writeable DB for practice : Phil uses "SQL Server (DSN)"...but also "SQL Server"

R Packages:
* leonjessen/PepTools -- fails on install w/ remotes, need to set R_REMOTES_NO_ERRORS_FROM_WARNINGS (package built on newer version of R)
- github keras (rstudio/keras)

**Comment by colearendt** [comment]
Disregard for now
