### ISSUE TITLE
Fix Java Issues

### ISSUE THREAD

**Issue by colearendt** [rstudio/sol-eng-demo-server#29]
For sparklyr, etc.

**Comment by colearendt** [comment]
This is a fix discussed on slack:
> Just to follow up on this one, setting /etc/rstudio/r-versions like this
```
Path: /opt/R/4.0.2
Script: /opt/R/4.0.2/lib/R/etc/ldpaths
```
> …did indeed fix the problem.

https://rstudio.slack.com/archives/C0DAAVDJQ/p1604518467332300?thread_ts=1603834915.269900&cid=C0DAAVDJQ

**Comment by colearendt** [comment]
This came up again today - write-up internally in #sol-eng-priv. We should really figure out a place to document / recommend this. It is particularly tricky to set up within the context of the helm chart

**Comment by colearendt** [comment]
Customer hit this and is trying to solve... but it seems not to be working. Anything we can do to clean this up would be well worth it! In particular, the differences between workbench, the session, etc. is very important / noteworthy.

**Comment by michaelmayer2** [comment]
For the general fix we have a support article https://support.rstudio.com/hc/en-us/articles/360058209074-Using-rJava-with-RStudio-Workbench-RStudio-Server-Pro-Launcher-and-Kubernetes

For more background we have a PR in solutions ==> https://github.com/rstudio/solutions.rstudio.com/pull/210

**Comment by colearendt** [comment]
Had a customer running into this issue - this ultimately sufficed for them, but they had `=` signs instead of `:`, courtesy of our helm chart 😭 DCF vs. INI nightmares

**Comment by edavidaja** [comment]
FYI https://solutions.rstudio.com/r/using-rjava/#additional-steps-for-rstudio-workbench

**Comment by colearendt** [comment]
Just FYI, we do _not_ want to put this file at `/etc/rstudio/r-versions` because Colorado does not use that `XDG_CONFIG_DIRS` path. We should probably use `/mnt/dynamic/rstudio/r-versions`, because IIRC that is used as-is on disk
